name: PR Project
description: Adds PR to specified project
branding:
  icon: 'eye'
  color: 'gray-dark'
author: Kirill Bubochkin
inputs:
  githubToken:
    description: 'GitHub token for commenting on a PR'
    default: ''
    required: true
  projectId:
    description: 'Project ID to add this PR to'
    default: ''
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
