name: Test project
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectId: MDc6UHJvamVjdDQ1NjA0NzM=
